# Loading A Sample of the Data Into Jupyter Notebook

In [ ]:
import pandas as pd

In [50]:
raw_data = pd.read_excel("Consumer Spending 1.xlsx")
raw_data

    % of Spending              Category  End Age  Start Age        Year Born
0           0.238  Restaurants_category     38.0         22        1981-1997
1           0.217    Groceries_category     38.0         22        1981-1997
2           0.108     Gasoline_category     38.0         22        1981-1997
3           0.030   Pharmacies_category     38.0         22        1981-1997
4           0.045     Building_category     38.0         22        1981-1997
5           0.045    Furniture_category     38.0         22        1981-1997
6           0.185         Elec_category     38.0         22        1981-1997
7           0.185      Hobbies_category     38.0         22        1981-1997
8           0.185     Clothing_category     38.0         22        1981-1997
9           0.177         Misc_category     38.0         22        1981-1997
10          0.177      General_category     38.0         22        1981-1997
11          0.177  Restaurants_category     54.0         39        1965-1980
12          0.253    Groceries_category     54.0         39        1965-1980
13          0.097     Gasoline_category     54.0         39        1965-1980
14          0.029   Pharmacies_category     54.0         39        1965-1980
15          0.073     Building_category     54.0         39        1965-1980
16          0.073    Furniture_category     54.0         39        1965-1980
17          0.168         Elec_category     54.0         39        1965-1980
18          0.168      Hobbies_category     54.0         39        1965-1980
19          0.168     Clothing_category     54.0         39        1965-1980
20          0.203         Misc_category     54.0         39        1965-1980
21          0.203      General_category     54.0         39        1965-1980
22          0.135  Restaurants_category     73.0         55        1946-1964
23          0.272    Groceries_category     73.0         55        1946-1964
24          0.085     Gasoline_category     73.0         55        1946-1964
25          0.037   Pharmacies_category     73.0         55        1946-1964
26          0.100     Building_category     73.0         55        1946-1964
27          0.100    Furniture_category     73.0         55        1946-1964
28          0.147         Elec_category     73.0         55        1946-1964
29          0.147      Hobbies_category     73.0         55        1946-1964
30          0.147     Clothing_category     73.0         55        1946-1964
31          0.223      General_category     73.0         55        1946-1964
32          0.223         Misc_category     73.0         55        1946-1964
33          0.128  Restaurants_category     38.0         22  1945 and before
34          0.304    Groceries_category     38.0         22  1945 and before
35          0.067     Gasoline_category     38.0         22  1945 and before
36          0.064   Pharmacies_category     38.0         22  1945 and before
37          0.094     Building_category     38.0         22  1945 and before
38          0.094    Furniture_category     38.0         22  1945 and before
39          0.118         Elec_category     38.0         22  1945 and before
40          0.118      Hobbies_category     38.0         22  1945 and before
41          0.118     Clothing_category     38.0         22  1945 and before
42          0.225         Misc_category     38.0         22  1945 and before
43          0.225      General_category     38.0         22  1945 and before

In [73]:
### data from a coworker
descript = pd.read_excel("Descriptions (1).xlsx")
descript = descript["Description"]
descript = descript[0:28]
descript

0     Millennials were born between 1981 and 1997.\n...
1     Millennials were born between 1981 and 1997.\n...
2     Millennials were born between 1981 and 1997.\n...
3     Millennials were born between 1981 and 1997.\n...
4     Millennials were born between 1981 and 1997.\n...
5     Millennials were born between 1981 and 1997.\n...
6     Millennials were born between 1981 and 1997.\n...
7     Generation Xers were born between 1965 and 198...
8     Generation Xers were born between 1965 and 198...
9     Generation Xers were born between 1965 and 198...
10    Generation Xers were born between 1965 and 198...
11    Generation Xers were born between 1965 and 198...
12    Generation Xers were born between 1965 and 198...
13    Generation Xers were born between 1965 and 198...
14    Baby Boomers were born between 1946 and 1964.\...
15    Baby Boomers were born between 1946 and 1964.\...
16    Baby Boomers were born between 1946 and 1964.\...
17    Baby Boomers were born between 1946 and 1964.\...
18    Baby Boomers were born between 1946 and 1964.\...
19    Baby Boomers were born between 1946 and 1964.\...
20    Baby Boomers were born between 1946 and 1964.\...
21    The traditionalist generation was born before ...
22    The traditionalist generation was born before ...
23    The traditionalist generation was born before ...
24    The traditionalist generation was born before ...
25    The traditionalist generation was born before ...
26    The traditionalist generation was born before ...
27    The traditionalist generation was born before ...
Name: Description, dtype: object

# Strip the word "category" in the Category column

In [52]:
raw_data["Category"] = raw_data["Category"].str.strip("category")
raw_data

    % of Spending      Category  End Age  Start Age        Year Born
0           0.238  Restaurants_     38.0         22        1981-1997
1           0.217    Groceries_     38.0         22        1981-1997
2           0.108     Gasoline_     38.0         22        1981-1997
3           0.030   Pharmacies_     38.0         22        1981-1997
4           0.045     Building_     38.0         22        1981-1997
5           0.045    Furniture_     38.0         22        1981-1997
6           0.185         Elec_     38.0         22        1981-1997
7           0.185      Hobbies_     38.0         22        1981-1997
8           0.185     Clothing_     38.0         22        1981-1997
9           0.177         Misc_     38.0         22        1981-1997
10          0.177      General_     38.0         22        1981-1997
11          0.177  Restaurants_     54.0         39        1965-1980
12          0.253    Groceries_     54.0         39        1965-1980
13          0.097     Gasoline_     54.0         39        1965-1980
14          0.029   Pharmacies_     54.0         39        1965-1980
15          0.073     Building_     54.0         39        1965-1980
16          0.073    Furniture_     54.0         39        1965-1980
17          0.168         Elec_     54.0         39        1965-1980
18          0.168      Hobbies_     54.0         39        1965-1980
19          0.168     Clothing_     54.0         39        1965-1980
20          0.203         Misc_     54.0         39        1965-1980
21          0.203      General_     54.0         39        1965-1980
22          0.135  Restaurants_     73.0         55        1946-1964
23          0.272    Groceries_     73.0         55        1946-1964
24          0.085     Gasoline_     73.0         55        1946-1964
25          0.037   Pharmacies_     73.0         55        1946-1964
26          0.100     Building_     73.0         55        1946-1964
27          0.100    Furniture_     73.0         55        1946-1964
28          0.147         Elec_     73.0         55        1946-1964
29          0.147      Hobbies_     73.0         55        1946-1964
30          0.147     Clothing_     73.0         55        1946-1964
31          0.223      General_     73.0         55        1946-1964
32          0.223         Misc_     73.0         55        1946-1964
33          0.128  Restaurants_     38.0         22  1945 and before
34          0.304    Groceries_     38.0         22  1945 and before
35          0.067     Gasoline_     38.0         22  1945 and before
36          0.064   Pharmacies_     38.0         22  1945 and before
37          0.094     Building_     38.0         22  1945 and before
38          0.094    Furniture_     38.0         22  1945 and before
39          0.118         Elec_     38.0         22  1945 and before
40          0.118      Hobbies_     38.0         22  1945 and before
41          0.118     Clothing_     38.0         22  1945 and before
42          0.225         Misc_     38.0         22  1945 and before
43          0.225      General_     38.0         22  1945 and before

In [53]:
raw_data["Category"] = raw_data["Category"].str.strip("_")
raw_data

    % of Spending     Category  End Age  Start Age        Year Born
0           0.238  Restaurants     38.0         22        1981-1997
1           0.217    Groceries     38.0         22        1981-1997
2           0.108     Gasoline     38.0         22        1981-1997
3           0.030   Pharmacies     38.0         22        1981-1997
4           0.045     Building     38.0         22        1981-1997
5           0.045    Furniture     38.0         22        1981-1997
6           0.185         Elec     38.0         22        1981-1997
7           0.185      Hobbies     38.0         22        1981-1997
8           0.185     Clothing     38.0         22        1981-1997
9           0.177         Misc     38.0         22        1981-1997
10          0.177      General     38.0         22        1981-1997
11          0.177  Restaurants     54.0         39        1965-1980
12          0.253    Groceries     54.0         39        1965-1980
13          0.097     Gasoline     54.0         39        1965-1980
14          0.029   Pharmacies     54.0         39        1965-1980
15          0.073     Building     54.0         39        1965-1980
16          0.073    Furniture     54.0         39        1965-1980
17          0.168         Elec     54.0         39        1965-1980
18          0.168      Hobbies     54.0         39        1965-1980
19          0.168     Clothing     54.0         39        1965-1980
20          0.203         Misc     54.0         39        1965-1980
21          0.203      General     54.0         39        1965-1980
22          0.135  Restaurants     73.0         55        1946-1964
23          0.272    Groceries     73.0         55        1946-1964
24          0.085     Gasoline     73.0         55        1946-1964
25          0.037   Pharmacies     73.0         55        1946-1964
26          0.100     Building     73.0         55        1946-1964
27          0.100    Furniture     73.0         55        1946-1964
28          0.147         Elec     73.0         55        1946-1964
29          0.147      Hobbies     73.0         55        1946-1964
30          0.147     Clothing     73.0         55        1946-1964
31          0.223      General     73.0         55        1946-1964
32          0.223         Misc     73.0         55        1946-1964
33          0.128  Restaurants     38.0         22  1945 and before
34          0.304    Groceries     38.0         22  1945 and before
35          0.067     Gasoline     38.0         22  1945 and before
36          0.064   Pharmacies     38.0         22  1945 and before
37          0.094     Building     38.0         22  1945 and before
38          0.094    Furniture     38.0         22  1945 and before
39          0.118         Elec     38.0         22  1945 and before
40          0.118      Hobbies     38.0         22  1945 and before
41          0.118     Clothing     38.0         22  1945 and before
42          0.225         Misc     38.0         22  1945 and before
43          0.225      General     38.0         22  1945 and before

# Convert float to integer data type in End Age column to remove the ".0"

In [54]:
raw_data["End Age"] = raw_data["End Age"].astype("int")
raw_data

    % of Spending     Category  End Age  Start Age        Year Born
0           0.238  Restaurants       38         22        1981-1997
1           0.217    Groceries       38         22        1981-1997
2           0.108     Gasoline       38         22        1981-1997
3           0.030   Pharmacies       38         22        1981-1997
4           0.045     Building       38         22        1981-1997
5           0.045    Furniture       38         22        1981-1997
6           0.185         Elec       38         22        1981-1997
7           0.185      Hobbies       38         22        1981-1997
8           0.185     Clothing       38         22        1981-1997
9           0.177         Misc       38         22        1981-1997
10          0.177      General       38         22        1981-1997
11          0.177  Restaurants       54         39        1965-1980
12          0.253    Groceries       54         39        1965-1980
13          0.097     Gasoline       54         39        1965-1980
14          0.029   Pharmacies       54         39        1965-1980
15          0.073     Building       54         39        1965-1980
16          0.073    Furniture       54         39        1965-1980
17          0.168         Elec       54         39        1965-1980
18          0.168      Hobbies       54         39        1965-1980
19          0.168     Clothing       54         39        1965-1980
20          0.203         Misc       54         39        1965-1980
21          0.203      General       54         39        1965-1980
22          0.135  Restaurants       73         55        1946-1964
23          0.272    Groceries       73         55        1946-1964
24          0.085     Gasoline       73         55        1946-1964
25          0.037   Pharmacies       73         55        1946-1964
26          0.100     Building       73         55        1946-1964
27          0.100    Furniture       73         55        1946-1964
28          0.147         Elec       73         55        1946-1964
29          0.147      Hobbies       73         55        1946-1964
30          0.147     Clothing       73         55        1946-1964
31          0.223      General       73         55        1946-1964
32          0.223         Misc       73         55        1946-1964
33          0.128  Restaurants       38         22  1945 and before
34          0.304    Groceries       38         22  1945 and before
35          0.067     Gasoline       38         22  1945 and before
36          0.064   Pharmacies       38         22  1945 and before
37          0.094     Building       38         22  1945 and before
38          0.094    Furniture       38         22  1945 and before
39          0.118         Elec       38         22  1945 and before
40          0.118      Hobbies       38         22  1945 and before
41          0.118     Clothing       38         22  1945 and before
42          0.225         Misc       38         22  1945 and before
43          0.225      General       38         22  1945 and before

# Set all elec, hobbies, clothing categories into Elec/Hobbies/Clothing because of high similarity/association

In [55]:
raw_data.loc[raw_data["Category"] == "Elec", "Category"] = "Elec/Hobbies/Clothing"
raw_data.loc[raw_data["Category"] == "Hobbies", "Category"] = "Elec/Hobbies/Clothing"
raw_data.loc[raw_data["Category"] == "Clothing", "Category"] = "Elec/Hobbies/Clothing"
raw_data

    % of Spending               Category  End Age  Start Age        Year Born
0           0.238            Restaurants       38         22        1981-1997
1           0.217              Groceries       38         22        1981-1997
2           0.108               Gasoline       38         22        1981-1997
3           0.030             Pharmacies       38         22        1981-1997
4           0.045               Building       38         22        1981-1997
5           0.045              Furniture       38         22        1981-1997
6           0.185  Elec/Hobbies/Clothing       38         22        1981-1997
7           0.185  Elec/Hobbies/Clothing       38         22        1981-1997
8           0.185  Elec/Hobbies/Clothing       38         22        1981-1997
9           0.177                   Misc       38         22        1981-1997
10          0.177                General       38         22        1981-1997
11          0.177            Restaurants       54         39        1965-1980
12          0.253              Groceries       54         39        1965-1980
13          0.097               Gasoline       54         39        1965-1980
14          0.029             Pharmacies       54         39        1965-1980
15          0.073               Building       54         39        1965-1980
16          0.073              Furniture       54         39        1965-1980
17          0.168  Elec/Hobbies/Clothing       54         39        1965-1980
18          0.168  Elec/Hobbies/Clothing       54         39        1965-1980
19          0.168  Elec/Hobbies/Clothing       54         39        1965-1980
20          0.203                   Misc       54         39        1965-1980
21          0.203                General       54         39        1965-1980
22          0.135            Restaurants       73         55        1946-1964
23          0.272              Groceries       73         55        1946-1964
24          0.085               Gasoline       73         55        1946-1964
25          0.037             Pharmacies       73         55        1946-1964
26          0.100               Building       73         55        1946-1964
27          0.100              Furniture       73         55        1946-1964
28          0.147  Elec/Hobbies/Clothing       73         55        1946-1964
29          0.147  Elec/Hobbies/Clothing       73         55        1946-1964
30          0.147  Elec/Hobbies/Clothing       73         55        1946-1964
31          0.223                General       73         55        1946-1964
32          0.223                   Misc       73         55        1946-1964
33          0.128            Restaurants       38         22  1945 and before
34          0.304              Groceries       38         22  1945 and before
35          0.067               Gasoline       38         22  1945 and before
36          0.064             Pharmacies       38         22  1945 and before
37          0.094               Building       38         22  1945 and before
38          0.094              Furniture       38         22  1945 and before
39          0.118  Elec/Hobbies/Clothing       38         22  1945 and before
40          0.118  Elec/Hobbies/Clothing       38         22  1945 and before
41          0.118  Elec/Hobbies/Clothing       38         22  1945 and before
42          0.225                   Misc       38         22  1945 and before
43          0.225                General       38         22  1945 and before

# Set all furniture and building to Furniture/Building
# Set all misc and general to General/Misc

In [56]:
raw_data.loc[raw_data["Category"] == "Furniture", "Category"] = "Furniture/Building"
raw_data.loc[raw_data["Category"] == "Building", "Category"] = "Furniture/Building"
raw_data

    % of Spending               Category  End Age  Start Age        Year Born
0           0.238            Restaurants       38         22        1981-1997
1           0.217              Groceries       38         22        1981-1997
2           0.108               Gasoline       38         22        1981-1997
3           0.030             Pharmacies       38         22        1981-1997
4           0.045     Furniture/Building       38         22        1981-1997
5           0.045     Furniture/Building       38         22        1981-1997
6           0.185  Elec/Hobbies/Clothing       38         22        1981-1997
7           0.185  Elec/Hobbies/Clothing       38         22        1981-1997
8           0.185  Elec/Hobbies/Clothing       38         22        1981-1997
9           0.177                   Misc       38         22        1981-1997
10          0.177                General       38         22        1981-1997
11          0.177            Restaurants       54         39        1965-1980
12          0.253              Groceries       54         39        1965-1980
13          0.097               Gasoline       54         39        1965-1980
14          0.029             Pharmacies       54         39        1965-1980
15          0.073     Furniture/Building       54         39        1965-1980
16          0.073     Furniture/Building       54         39        1965-1980
17          0.168  Elec/Hobbies/Clothing       54         39        1965-1980
18          0.168  Elec/Hobbies/Clothing       54         39        1965-1980
19          0.168  Elec/Hobbies/Clothing       54         39        1965-1980
20          0.203                   Misc       54         39        1965-1980
21          0.203                General       54         39        1965-1980
22          0.135            Restaurants       73         55        1946-1964
23          0.272              Groceries       73         55        1946-1964
24          0.085               Gasoline       73         55        1946-1964
25          0.037             Pharmacies       73         55        1946-1964
26          0.100     Furniture/Building       73         55        1946-1964
27          0.100     Furniture/Building       73         55        1946-1964
28          0.147  Elec/Hobbies/Clothing       73         55        1946-1964
29          0.147  Elec/Hobbies/Clothing       73         55        1946-1964
30          0.147  Elec/Hobbies/Clothing       73         55        1946-1964
31          0.223                General       73         55        1946-1964
32          0.223                   Misc       73         55        1946-1964
33          0.128            Restaurants       38         22  1945 and before
34          0.304              Groceries       38         22  1945 and before
35          0.067               Gasoline       38         22  1945 and before
36          0.064             Pharmacies       38         22  1945 and before
37          0.094     Furniture/Building       38         22  1945 and before
38          0.094     Furniture/Building       38         22  1945 and before
39          0.118  Elec/Hobbies/Clothing       38         22  1945 and before
40          0.118  Elec/Hobbies/Clothing       38         22  1945 and before
41          0.118  Elec/Hobbies/Clothing       38         22  1945 and before
42          0.225                   Misc       38         22  1945 and before
43          0.225                General       38         22  1945 and before

In [57]:
raw_data.loc[raw_data["Category"] == "Misc", "Category"] = "General/Misc"
raw_data.loc[raw_data["Category"] == "General", "Category"] = "General/Misc"
raw_data

    % of Spending               Category  End Age  Start Age        Year Born
0           0.238            Restaurants       38         22        1981-1997
1           0.217              Groceries       38         22        1981-1997
2           0.108               Gasoline       38         22        1981-1997
3           0.030             Pharmacies       38         22        1981-1997
4           0.045     Furniture/Building       38         22        1981-1997
5           0.045     Furniture/Building       38         22        1981-1997
6           0.185  Elec/Hobbies/Clothing       38         22        1981-1997
7           0.185  Elec/Hobbies/Clothing       38         22        1981-1997
8           0.185  Elec/Hobbies/Clothing       38         22        1981-1997
9           0.177           General/Misc       38         22        1981-1997
10          0.177           General/Misc       38         22        1981-1997
11          0.177            Restaurants       54         39        1965-1980
12          0.253              Groceries       54         39        1965-1980
13          0.097               Gasoline       54         39        1965-1980
14          0.029             Pharmacies       54         39        1965-1980
15          0.073     Furniture/Building       54         39        1965-1980
16          0.073     Furniture/Building       54         39        1965-1980
17          0.168  Elec/Hobbies/Clothing       54         39        1965-1980
18          0.168  Elec/Hobbies/Clothing       54         39        1965-1980
19          0.168  Elec/Hobbies/Clothing       54         39        1965-1980
20          0.203           General/Misc       54         39        1965-1980
21          0.203           General/Misc       54         39        1965-1980
22          0.135            Restaurants       73         55        1946-1964
23          0.272              Groceries       73         55        1946-1964
24          0.085               Gasoline       73         55        1946-1964
25          0.037             Pharmacies       73         55        1946-1964
26          0.100     Furniture/Building       73         55        1946-1964
27          0.100     Furniture/Building       73         55        1946-1964
28          0.147  Elec/Hobbies/Clothing       73         55        1946-1964
29          0.147  Elec/Hobbies/Clothing       73         55        1946-1964
30          0.147  Elec/Hobbies/Clothing       73         55        1946-1964
31          0.223           General/Misc       73         55        1946-1964
32          0.223           General/Misc       73         55        1946-1964
33          0.128            Restaurants       38         22  1945 and before
34          0.304              Groceries       38         22  1945 and before
35          0.067               Gasoline       38         22  1945 and before
36          0.064             Pharmacies       38         22  1945 and before
37          0.094     Furniture/Building       38         22  1945 and before
38          0.094     Furniture/Building       38         22  1945 and before
39          0.118  Elec/Hobbies/Clothing       38         22  1945 and before
40          0.118  Elec/Hobbies/Clothing       38         22  1945 and before
41          0.118  Elec/Hobbies/Clothing       38         22  1945 and before
42          0.225           General/Misc       38         22  1945 and before
43          0.225           General/Misc       38         22  1945 and before

# Now reduce the number of duplicate rows

In [58]:
raw_data[6:9] = raw_data[6:9].drop_duplicates()
raw_data[17:20] = raw_data[17:20].drop_duplicates()
raw_data[28:31] = raw_data[28:31].drop_duplicates()
raw_data[39:42] = raw_data[39:42].drop_duplicates()
raw_data[17:20] = raw_data[17:20].drop_duplicates()
raw_data[4:6] = raw_data[4:6].drop_duplicates()
raw_data[15:17] = raw_data[15:17].drop_duplicates()
raw_data[26:28] = raw_data[26:28].drop_duplicates()
raw_data[37:39] = raw_data[37:39].drop_duplicates()
raw_data[17:20] = raw_data[17:20].drop_duplicates()
raw_data[9:11] = raw_data[9:11].drop_duplicates()
raw_data[20:22] = raw_data[20:22].drop_duplicates()
raw_data[31:33] = raw_data[31:33].drop_duplicates()
raw_data[42:44] = raw_data[42:44].drop_duplicates()
raw_data

    % of Spending               Category  End Age  Start Age        Year Born
0           0.238            Restaurants     38.0       22.0        1981-1997
1           0.217              Groceries     38.0       22.0        1981-1997
2           0.108               Gasoline     38.0       22.0        1981-1997
3           0.030             Pharmacies     38.0       22.0        1981-1997
4           0.045     Furniture/Building     38.0       22.0        1981-1997
5             NaN                    NaN      NaN        NaN              NaN
6           0.185  Elec/Hobbies/Clothing     38.0       22.0        1981-1997
7             NaN                    NaN      NaN        NaN              NaN
8             NaN                    NaN      NaN        NaN              NaN
9           0.177           General/Misc     38.0       22.0        1981-1997
10            NaN                    NaN      NaN        NaN              NaN
11          0.177            Restaurants     54.0       39.0        1965-1980
12          0.253              Groceries     54.0       39.0        1965-1980
13          0.097               Gasoline     54.0       39.0        1965-1980
14          0.029             Pharmacies     54.0       39.0        1965-1980
15          0.073     Furniture/Building     54.0       39.0        1965-1980
16            NaN                    NaN      NaN        NaN              NaN
17          0.168  Elec/Hobbies/Clothing     54.0       39.0        1965-1980
18            NaN                    NaN      NaN        NaN              NaN
19            NaN                    NaN      NaN        NaN              NaN
20          0.203           General/Misc     54.0       39.0        1965-1980
21            NaN                    NaN      NaN        NaN              NaN
22          0.135            Restaurants     73.0       55.0        1946-1964
23          0.272              Groceries     73.0       55.0        1946-1964
24          0.085               Gasoline     73.0       55.0        1946-1964
25          0.037             Pharmacies     73.0       55.0        1946-1964
26          0.100     Furniture/Building     73.0       55.0        1946-1964
27            NaN                    NaN      NaN        NaN              NaN
28          0.147  Elec/Hobbies/Clothing     73.0       55.0        1946-1964
29            NaN                    NaN      NaN        NaN              NaN
30            NaN                    NaN      NaN        NaN              NaN
31          0.223           General/Misc     73.0       55.0        1946-1964
32            NaN                    NaN      NaN        NaN              NaN
33          0.128            Restaurants     38.0       22.0  1945 and before
34          0.304              Groceries     38.0       22.0  1945 and before
35          0.067               Gasoline     38.0       22.0  1945 and before
36          0.064             Pharmacies     38.0       22.0  1945 and before
37          0.094     Furniture/Building     38.0       22.0  1945 and before
38            NaN                    NaN      NaN        NaN              NaN
39          0.118  Elec/Hobbies/Clothing     38.0       22.0  1945 and before
40            NaN                    NaN      NaN        NaN              NaN
41            NaN                    NaN      NaN        NaN              NaN
42          0.225           General/Misc     38.0       22.0  1945 and before
43            NaN                    NaN      NaN        NaN              NaN

In [61]:
### drop NAN rows
raw_data = raw_data.dropna()
raw_data

    % of Spending               Category  End Age  Start Age        Year Born
0           0.238            Restaurants     38.0       22.0        1981-1997
1           0.217              Groceries     38.0       22.0        1981-1997
2           0.108               Gasoline     38.0       22.0        1981-1997
3           0.030             Pharmacies     38.0       22.0        1981-1997
4           0.045     Furniture/Building     38.0       22.0        1981-1997
6           0.185  Elec/Hobbies/Clothing     38.0       22.0        1981-1997
9           0.177           General/Misc     38.0       22.0        1981-1997
11          0.177            Restaurants     54.0       39.0        1965-1980
12          0.253              Groceries     54.0       39.0        1965-1980
13          0.097               Gasoline     54.0       39.0        1965-1980
14          0.029             Pharmacies     54.0       39.0        1965-1980
15          0.073     Furniture/Building     54.0       39.0        1965-1980
17          0.168  Elec/Hobbies/Clothing     54.0       39.0        1965-1980
20          0.203           General/Misc     54.0       39.0        1965-1980
22          0.135            Restaurants     73.0       55.0        1946-1964
23          0.272              Groceries     73.0       55.0        1946-1964
24          0.085               Gasoline     73.0       55.0        1946-1964
25          0.037             Pharmacies     73.0       55.0        1946-1964
26          0.100     Furniture/Building     73.0       55.0        1946-1964
28          0.147  Elec/Hobbies/Clothing     73.0       55.0        1946-1964
31          0.223           General/Misc     73.0       55.0        1946-1964
33          0.128            Restaurants     38.0       22.0  1945 and before
34          0.304              Groceries     38.0       22.0  1945 and before
35          0.067               Gasoline     38.0       22.0  1945 and before
36          0.064             Pharmacies     38.0       22.0  1945 and before
37          0.094     Furniture/Building     38.0       22.0  1945 and before
39          0.118  Elec/Hobbies/Clothing     38.0       22.0  1945 and before
42          0.225           General/Misc     38.0       22.0  1945 and before

In [64]:
### reset index
raw_data = raw_data.reset_index()
raw_data.head()

,level_0,index,% of Spending,Category,End Age,Start Age,Year Born,Generation (Generation details),Generation,Color Order
0,0,0,0.238,Restaurants,38.0,22.0,1981-1997,1,1,1
1,1,1,0.217,Groceries,38.0,22.0,1981-1997,1,1,1
2,2,2,0.108,Gasoline,38.0,22.0,1981-1997,1,1,1
3,3,3,0.030,Pharmacies,38.0,22.0,1981-1997,1,1,1
4,4,4,0.045,Furniture/Building,38.0,22.0,1981-1997,1,1,1

# Create columns Generation (Generation details), Generation and Color Order using the Year Born column

In [62]:
raw_data["Generation (Generation details)"] = 1
raw_data["Generation"] = 1
raw_data["Color Order"] = 1
raw_data

,% of Spending,Category,End Age,Start Age,Year Born,Generation (Generation details),Generation,Color Order
0,0.238,Restaurants,38.0,22.0,1981-1997,1,1,1
1,0.217,Groceries,38.0,22.0,1981-1997,1,1,1
2,0.108,Gasoline,38.0,22.0,1981-1997,1,1,1
3,0.030,Pharmacies,38.0,22.0,1981-1997,1,1,1
4,0.045,Furniture/Building,38.0,22.0,1981-1997,1,1,1
6,0.185,Elec/Hobbies/Clothing,38.0,22.0,1981-1997,1,1,1
9,0.177,General/Misc,38.0,22.0,1981-1997,1,1,1
11,0.177,Restaurants,54.0,39.0,1965-1980,1,1,1
12,0.253,Groceries,54.0,39.0,1965-1980,1,1,1
13,0.097,Gasoline,54.0,39.0,1965-1980,1,1,1
14,0.029,Pharmacies,54.0,39.0,1965-1980,1,1,1
15,0.073,Furniture/Building,54.0,39.0,1965-1980,1,1,1
17,0.168,Elec/Hobbies/Clothing,54.0,39.0,1965-1980,1,1,1
20,0.203,General/Misc,54.0,39.0,1965-1980,1,1,1
22,0.135,Restaurants,73.0,55.0,1946-1964,1,1,1
23,0.272,Groceries,73.0,55.0,1946-1964,1,1,1
24,0.085,Gasoline,73.0,55.0,1946-1964,1,1,1
25,0.037,Pharmacies,73.0,55.0,1946-1964,1,1,1
26,0.100,Furniture/Building,73.0,55.0,1946-1964,1,1,1
28,0.147,Elec/Hobbies/Clothing,73.0,55.0,1946-1964,1,1,1
31,0.223,General/Misc,73.0,55.0,1946-1964,1,1,1
33,0.128,Restaurants,38.0,22.0,1945 and before,1,1,1
34,0.304,Groceries,38.0,22.0,1945 and before,1,1,1
35,0.067,Gasoline,38.0,22.0,1945 and before,1,1,1
36,0.064,Pharmacies,38.0,22.0,1945 and before,1,1,1
37,0.094,Furniture/Building,38.0,22.0,1945 and before,1,1,1
39,0.118,Elec/Hobbies/Clothing,38.0,22.0,1945 and before,1,1,1
42,0.225,General/Misc,38.0,22.0,1945 and before,1,1,1

In [70]:
for i in list(range(len(raw_data))):
    if raw_data["Year Born"][i] == "1981-1997":
        raw_data["Generation"] = "Millenials"
    elif raw_data["Year Born"][i] == "1965-1980":
        raw_data["Generation"][i] = "Generation X"
    elif raw_data["Year Born"][i] == "1946-1964":
        raw_data["Generation"][i] ="Baby Boomers"
    else:
        raw_data["Generation"][i] = "Traditionalists"
raw_data

<ipython-input-70-98b1792d2945>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_data["Generation"][i] = "Generation X"
<ipython-input-70-98b1792d2945>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_data["Generation"][i] ="Baby Boomers"
<ipython-input-70-98b1792d2945>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_data["Generation"][i] = "Traditionalists"

,level_0,index,% of Spending,Category,End Age,Start Age,Year Born,Generation (Generation details),Generation,Color Order
0,0,0,0.238,Restaurants,38.0,22.0,1981-1997,1,Millenials,1
1,1,1,0.217,Groceries,38.0,22.0,1981-1997,1,Millenials,1
2,2,2,0.108,Gasoline,38.0,22.0,1981-1997,1,Millenials,1
3,3,3,0.030,Pharmacies,38.0,22.0,1981-1997,1,Millenials,1
4,4,4,0.045,Furniture/Building,38.0,22.0,1981-1997,1,Millenials,1
5,5,6,0.185,Elec/Hobbies/Clothing,38.0,22.0,1981-1997,1,Millenials,1
6,6,9,0.177,General/Misc,38.0,22.0,1981-1997,1,Millenials,1
7,7,11,0.177,Restaurants,54.0,39.0,1965-1980,1,Generation X,1
8,8,12,0.253,Groceries,54.0,39.0,1965-1980,1,Generation X,1
9,9,13,0.097,Gasoline,54.0,39.0,1965-1980,1,Generation X,1
10,10,14,0.029,Pharmacies,54.0,39.0,1965-1980,1,Generation X,1
11,11,15,0.073,Furniture/Building,54.0,39.0,1965-1980,1,Generation X,1
12,12,17,0.168,Elec/Hobbies/Clothing,54.0,39.0,1965-1980,1,Generation X,1
13,13,20,0.203,General/Misc,54.0,39.0,1965-1980,1,Generation X,1
14,14,22,0.135,Restaurants,73.0,55.0,1946-1964,1,Baby Boomers,1
15,15,23,0.272,Groceries,73.0,55.0,1946-1964,1,Baby Boomers,1
16,16,24,0.085,Gasoline,73.0,55.0,1946-1964,1,Baby Boomers,1
17,17,25,0.037,Pharmacies,73.0,55.0,1946-1964,1,Baby Boomers,1
18,18,26,0.100,Furniture/Building,73.0,55.0,1946-1964,1,Baby Boomers,1
19,19,28,0.147,Elec/Hobbies/Clothing,73.0,55.0,1946-1964,1,Baby Boomers,1
20,20,31,0.223,General/Misc,73.0,55.0,1946-1964,1,Baby Boomers,1
21,21,33,0.128,Restaurants,38.0,22.0,1945 and before,1,Traditionalists,1
22,22,34,0.304,Groceries,38.0,22.0,1945 and before,1,Traditionalists,1
23,23,35,0.067,Gasoline,38.0,22.0,1945 and before,1,Traditionalists,1
24,24,36,0.064,Pharmacies,38.0,22.0,1945 and before,1,Traditionalists,1
25,25,37,0.094,Furniture/Building,38.0,22.0,1945 and before,1,Traditionalists,1
26,26,39,0.118,Elec/Hobbies/Clothing,38.0,22.0,1945 and before,1,Traditionalists,1
27,27,42,0.225,General/Misc,38.0,22.0,1945 and before,1,Traditionalists,1

In [71]:
raw_data["Generation (Generation details)"] = raw_data["Generation"]
raw_data["Color Order"] = raw_data["Generation"]
raw_data

,level_0,index,% of Spending,Category,End Age,Start Age,Year Born,Generation (Generation details),Generation,Color Order
0,0,0,0.238,Restaurants,38.0,22.0,1981-1997,Millenials,Millenials,Millenials
1,1,1,0.217,Groceries,38.0,22.0,1981-1997,Millenials,Millenials,Millenials
2,2,2,0.108,Gasoline,38.0,22.0,1981-1997,Millenials,Millenials,Millenials
3,3,3,0.030,Pharmacies,38.0,22.0,1981-1997,Millenials,Millenials,Millenials
4,4,4,0.045,Furniture/Building,38.0,22.0,1981-1997,Millenials,Millenials,Millenials
5,5,6,0.185,Elec/Hobbies/Clothing,38.0,22.0,1981-1997,Millenials,Millenials,Millenials
6,6,9,0.177,General/Misc,38.0,22.0,1981-1997,Millenials,Millenials,Millenials
7,7,11,0.177,Restaurants,54.0,39.0,1965-1980,Generation X,Generation X,Generation X
8,8,12,0.253,Groceries,54.0,39.0,1965-1980,Generation X,Generation X,Generation X
9,9,13,0.097,Gasoline,54.0,39.0,1965-1980,Generation X,Generation X,Generation X
10,10,14,0.029,Pharmacies,54.0,39.0,1965-1980,Generation X,Generation X,Generation X
11,11,15,0.073,Furniture/Building,54.0,39.0,1965-1980,Generation X,Generation X,Generation X
12,12,17,0.168,Elec/Hobbies/Clothing,54.0,39.0,1965-1980,Generation X,Generation X,Generation X
13,13,20,0.203,General/Misc,54.0,39.0,1965-1980,Generation X,Generation X,Generation X
14,14,22,0.135,Restaurants,73.0,55.0,1946-1964,Baby Boomers,Baby Boomers,Baby Boomers
15,15,23,0.272,Groceries,73.0,55.0,1946-1964,Baby Boomers,Baby Boomers,Baby Boomers
16,16,24,0.085,Gasoline,73.0,55.0,1946-1964,Baby Boomers,Baby Boomers,Baby Boomers
17,17,25,0.037,Pharmacies,73.0,55.0,1946-1964,Baby Boomers,Baby Boomers,Baby Boomers
18,18,26,0.100,Furniture/Building,73.0,55.0,1946-1964,Baby Boomers,Baby Boomers,Baby Boomers
19,19,28,0.147,Elec/Hobbies/Clothing,73.0,55.0,1946-1964,Baby Boomers,Baby Boomers,Baby Boomers
20,20,31,0.223,General/Misc,73.0,55.0,1946-1964,Baby Boomers,Baby Boomers,Baby Boomers
21,21,33,0.128,Restaurants,38.0,22.0,1945 and before,Traditionalists,Traditionalists,Traditionalists
22,22,34,0.304,Groceries,38.0,22.0,1945 and before,Traditionalists,Traditionalists,Traditionalists
23,23,35,0.067,Gasoline,38.0,22.0,1945 and before,Traditionalists,Traditionalists,Traditionalists
24,24,36,0.064,Pharmacies,38.0,22.0,1945 and before,Traditionalists,Traditionalists,Traditionalists
25,25,37,0.094,Furniture/Building,38.0,22.0,1945 and before,Traditionalists,Traditionalists,Traditionalists
26,26,39,0.118,Elec/Hobbies/Clothing,38.0,22.0,1945 and before,Traditionalists,Traditionalists,Traditionalists
27,27,42,0.225,General/Misc,38.0,22.0,1945 and before,Traditionalists,Traditionalists,Traditionalists

# Join the description column given by coworker

In [74]:
d = {'index': list(range(len(raw_data))), 'Description': descript}
description = pd.DataFrame(data=d)

In [75]:
description

    index                                        Description
0       0  Millennials were born between 1981 and 1997.\n...
1       1  Millennials were born between 1981 and 1997.\n...
2       2  Millennials were born between 1981 and 1997.\n...
3       3  Millennials were born between 1981 and 1997.\n...
4       4  Millennials were born between 1981 and 1997.\n...
5       5  Millennials were born between 1981 and 1997.\n...
6       6  Millennials were born between 1981 and 1997.\n...
7       7  Generation Xers were born between 1965 and 198...
8       8  Generation Xers were born between 1965 and 198...
9       9  Generation Xers were born between 1965 and 198...
10     10  Generation Xers were born between 1965 and 198...
11     11  Generation Xers were born between 1965 and 198...
12     12  Generation Xers were born between 1965 and 198...
13     13  Generation Xers were born between 1965 and 198...
14     14  Baby Boomers were born between 1946 and 1964.\...
15     15  Baby Boomers were born between 1946 and 1964.\...
16     16  Baby Boomers were born between 1946 and 1964.\...
17     17  Baby Boomers were born between 1946 and 1964.\...
18     18  Baby Boomers were born between 1946 and 1964.\...
19     19  Baby Boomers were born between 1946 and 1964.\...
20     20  Baby Boomers were born between 1946 and 1964.\...
21     21  The traditionalist generation was born before ...
22     22  The traditionalist generation was born before ...
23     23  The traditionalist generation was born before ...
24     24  The traditionalist generation was born before ...
25     25  The traditionalist generation was born before ...
26     26  The traditionalist generation was born before ...
27     27  The traditionalist generation was born before ...

In [76]:
raw_data = raw_data.merge(description, on="index", how="inner")
raw_data

,level_0,index,% of Spending,Category,End Age,Start Age,Year Born,Generation (Generation details),Generation,Color Order,Description
0,0,0,0.238,Restaurants,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
1,1,1,0.217,Groceries,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
2,2,2,0.108,Gasoline,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
3,3,3,0.030,Pharmacies,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
4,4,4,0.045,Furniture/Building,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
5,5,6,0.185,Elec/Hobbies/Clothing,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
6,6,9,0.177,General/Misc,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Generation Xers were born between 1965 and 198...
7,7,11,0.177,Restaurants,54.0,39.0,1965-1980,Generation X,Generation X,Generation X,Generation Xers were born between 1965 and 198...
8,8,12,0.253,Groceries,54.0,39.0,1965-1980,Generation X,Generation X,Generation X,Generation Xers were born between 1965 and 198...
9,9,13,0.097,Gasoline,54.0,39.0,1965-1980,Generation X,Generation X,Generation X,Generation Xers were born between 1965 and 198...
10,10,14,0.029,Pharmacies,54.0,39.0,1965-1980,Generation X,Generation X,Generation X,Baby Boomers were born between 1946 and 1964.\...
11,11,15,0.073,Furniture/Building,54.0,39.0,1965-1980,Generation X,Generation X,Generation X,Baby Boomers were born between 1946 and 1964.\...
12,12,17,0.168,Elec/Hobbies/Clothing,54.0,39.0,1965-1980,Generation X,Generation X,Generation X,Baby Boomers were born between 1946 and 1964.\...
13,13,20,0.203,General/Misc,54.0,39.0,1965-1980,Generation X,Generation X,Generation X,Baby Boomers were born between 1946 and 1964.\...
14,14,22,0.135,Restaurants,73.0,55.0,1946-1964,Baby Boomers,Baby Boomers,Baby Boomers,The traditionalist generation was born before ...
15,15,23,0.272,Groceries,73.0,55.0,1946-1964,Baby Boomers,Baby Boomers,Baby Boomers,The traditionalist generation was born before ...
16,16,24,0.085,Gasoline,73.0,55.0,1946-1964,Baby Boomers,Baby Boomers,Baby Boomers,The traditionalist generation was born before ...
17,17,25,0.037,Pharmacies,73.0,55.0,1946-1964,Baby Boomers,Baby Boomers,Baby Boomers,The traditionalist generation was born before ...
18,18,26,0.100,Furniture/Building,73.0,55.0,1946-1964,Baby Boomers,Baby Boomers,Baby Boomers,The traditionalist generation was born before ...

In [86]:
### remove the level_0 column
raw_data = raw_data.drop(columns="level_0").head()
raw_data

,index,% of Spending,Category,End Age,Start Age,Year Born,Generation (Generation details),Generation,Color Order,Description
0,0,0.238,Restaurants,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
1,1,0.217,Groceries,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
2,2,0.108,Gasoline,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
3,3,0.030,Pharmacies,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
4,4,0.045,Furniture/Building,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...

In [87]:
# remove the index column
raw_data = raw_data.drop(columns="index").head()
raw_data

,% of Spending,Category,End Age,Start Age,Year Born,Generation (Generation details),Generation,Color Order,Description
0,0.238,Restaurants,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
1,0.217,Groceries,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
2,0.108,Gasoline,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
3,0.030,Pharmacies,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
4,0.045,Furniture/Building,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...

In [88]:
raw_data

,% of Spending,Category,End Age,Start Age,Year Born,Generation (Generation details),Generation,Color Order,Description
0,0.238,Restaurants,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
1,0.217,Groceries,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
2,0.108,Gasoline,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
3,0.030,Pharmacies,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...
4,0.045,Furniture/Building,38.0,22.0,1981-1997,Millenials,Millenials,Millenials,Millennials were born between 1981 and 1997.\n...

# Save The Cleaned & Transformed Data Set

In [ ]:
raw_data.to_excel("Consumer Spending.xlsx")